all: part1 part2

part1: assignment2_part1.c
		gcc -pthread -o part1.out assignment2_part1.c

part2: assignment2_part2.c
		gcc -o part2.out assignment2_part2.c

clean:
		-rm *.out cpu_scheduling_output_file.txt
